----------------------------------------------DATE : 19-seot-2022------------------------------------------------------------------- 


#include <iostream>
using namespace std;
int main() {
    
    for (int i = 1; i <= 4; i++){
        for(int j = 1;j<=4; j++){
            cout<<"*";
        }
    cout<<endl;
        
    }

    return 0;
}

OUTPUT----------------------------------------
****
****
****
****



#include <iostream>
using namespace std;
int main() {
    
    for (int i = 1; i <= 4; i++){
        for(int j = 1;j<=4; j++){
            cout<<j;
        }
    cout<<endl;
        
    }

    return 0;
}

OUTPUT
1234
1234
1234
1234

